FLASK_APP=Myapp.py
FLASK_DEBUG=True

MAIL_SERVER='smtp.mailtrap.io'
MAIL_PORT = 2525
MAIL_USERNAME = '54a714b8e6914c'
MAIL_PASSWORD = 'f02696f6dccbef'
MAIL_USE_TLS = True
MAIL_USE_SSL = False

FLASKY_ADMIN='bob@bob.com'